### ISSUE TITLE
chess command

### ISSUE THREAD

**Issue by digasred** [Winston-Lu/Discord.py-Potato-Bot#3]

**Comment by digasred** [comment]
getting this error: 
async for x in ctx.channel.history(limit = number):
AttributeError: 'int' object has no attribute 'channel'

**Comment by digasred** [comment]
i fix it but now when i type the pieces they wont move any help ?

**Comment by Winston-Lu** [comment]
The chess game is still in development. Haven't gotten around to working on it or testing it recently. If you have any suggestions feel free to send a fork request

**Comment by Winston-Lu** [comment]
Finally got around to fixing it. Should work now
